version: 2
jobs:
  build:
    docker:
      - image: node:carbon
    working_directory: ~/ci-museeks
    steps:
      - checkout
      - run:
          name: Display node and npm informations
          command: |
            echo "node version $(node -v) running"
            echo "npm version $(npm -v) running"
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - mpm-cache
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: "Lint check: JS"
          command: "npm run lint:js"
      - run:
          name: "Lint check: Sass"
          command: "npm run lint:sass"
      - run:
          name: Build application
          command: npm run build
      - save_cache:
          paths:
            - ./node_modules
          key: npm-cache-{{ checksum "package-lock.json" }}
